spring:
  profiles:
    active: prod

---


spring:
  application:
    name: report
  server:
    port: 8080
    servlet:
      context-path: /api
    error:
      include-message: always
external-api:
  baseUrl: https://hygieia.fast-report.com/
  login: apikey
  token: toinotuk6cspof759edm7sxto81dhxur6s89pfm3e3bxh1ce8kuo

cors:
  origin: ${CORS_ORIGIN}